#!/bin/bash

ARCHS=(amd64 arm64 armel armhf mips64el mipsel ppc64el s390x)
FILES=(desktop desktop-recommends live minimal minimal-recommends standard standard-recommends)

for a in ${ARCHS[*]}; do
  for f in ${FILES[*]}; do
    filename=$f-$a
    if [ -f $filename ]; then
      echo "Removing $filename"
      rm $filename
    else
      echo "$filename doesn't exist-not removing"
    fi
  done
done
