#!/bin/bash

ARCHS=(amd64 arm64 armel armhf mips64el mipsel ppc64el s390x)
FILES=(desktop desktop-recommends live minimal minimal-recommends standard standard-recommends)
for a in ${ARCHS[*]};
do
  for f in ${FILES[*]}
  do
    cp ${f[@]} ./${f}-${a}
  done
done
